// <auto-generated />
namespace CZE_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OcjeneOpis_GrupaSlikeHCI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OcjeneOpis_GrupaSlikeHCI));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141032595_Ocjene-Opis_Grupa-Slike-HCI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
