// <auto-generated />
namespace CZE_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CertifikatiGrupeKandidati_One2One_V1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CertifikatiGrupeKandidati_One2One_V1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707080912165_Certifikati-GrupeKandidati_One2One_V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
